# Generated by Django 2.2.12 on 2020-08-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cv_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CV_page',
            new_name='CV_list',
        ),
    ]
