# Generated by Django 2.2.12 on 2020-08-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200813_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv_list',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cv_list',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='cv_list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cv_list',
            name='phone',
        ),
    ]
