# Generated by Django 2.2.12 on 2020-08-17 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200816_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv_list',
            name='title',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
