# Generated by Django 2.2.12 on 2020-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_cv_list_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv_list',
            name='author',
        ),
    ]
